models/movie_list.py
import uuid

from extensions import db


class Movie_List(db.Model):
    __tablename__ = "movies-list"
    id = db.Column(db.String(50), primary_key=True, default=lambda: str(uuid.uuid4()))
    name = db.Column(db.String(100))
    poster = db.Column(db.String(255))
    rating = db.Column(db.Float)
    summary = db.Column(db.String(500))
    trailer = db.Column(db.String(255))

    # Object -> Dict
    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "poster": self.poster,
            "rating": self.rating,
            "summary": self.summary,
            "trailer": self.trailer,
        }

routes/movies_list_bp.py
from pprint import pprint

from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_required

from contstants import STATUS_CODE
from extensions import db
from models.movie import Movie

# 1. Organize
# 2. app needs to be in main.py
movies_list_bp = Blueprint("movies_list_bp", __name__)


# Fullstack Developer
# /movies -> movies
@movies_list_bp.get("/")
@login_required
def movie_list_page():
    movies = Movie.query.all()  # Select * from movies
    movies_dict = [movie.to_dict() for movie in movies]
    return render_template("movie-list.html", movies=movies_dict)


# /movies/100 - <id> -> Variable
@movies_list_bp.get("/<id>")
def movie_details_page(id):
    movie = Movie.query.get(id)  # None if no movie

    if not movie:
        return render_template("not-found.html"), STATUS_CODE["NOT_FOUND"]

    data = movie.to_dict()
    return render_template("movie-details.html", movie=data)


@movies_list_bp.get("/new")
def add_movie_page():
    return render_template("add-movie.html")


@movies_list_bp.post("/")  # HOF
def create_movie():
    data = {
        "name": request.form.get("name"),
        "poster": request.form.get("poster"),
        "rating": request.form.get("rating"),
        "summary": request.form.get("summary"),
        "trailer": request.form.get("trailer"),
    }
    # data = request.get_json()  # body
    new_movie = Movie(**data)

    try:
        # print(new_movie, new_movie.to_dict())
        db.session.add(new_movie)
        db.session.commit()
        return redirect(url_for("movies_list_bp.movie_list_page"))
    except Exception as e:
        db.session.rollback()  # Undo: Restore the data | After commit cannot undo
        return redirect(url_for("movies_list_bp.add_movie_page"))


@movies_list_bp.delete("/<id>")
def delete_movie_by_id(id):  # log
    # Auto converts data -> JSON (Flask)

    movie = Movie.query.get(id)
    if not movie:
        return {"message": "Movie not found"}, STATUS_CODE["NOT FOUND"]

    try:
        data = movie.to_dict()
        db.session.delete(movie)

        db.session.commit()  # Making the change (Update/Delete/Create)
        return redirect(url_for("movies_list_bp.movie_list_page"))
    except Exception as e:
        db.session.rollback()
        return redirect(url_for("movies_list_bp.movie_list_page"))

templates/about.html
{% extends "base.html" %} {% block head_content %}
<style>
  .highlight {
    color: orange;
  }
</style>
{% endblock %} {% block content %}

<h1>Hello, <span class="highlight">{{name}}</span> 😊</h1>
<p>Your are super nice, {{name}}.</p>
<!-- Task 1.2: List all hobbies - ul  -->
<h2>Hobbies</h2>
<ul>
  {% for hobby in hobbies %}

  <li>{{hobby}}</li>

  {% endfor %}
</ul>

{% endblock %}

templates/add-movie.html
{% extends "base.html" %} {% block head_content %}
<style>
  .form-element {
    display: flex;
    flex-direction: column;
  }

  .form-container {
    display: flex;
    flex-direction: column;
    gap: 16px;
    max-width: 500px;
  }
</style>
{% endblock %} {% block content %}

<!-- BP.FN -->
<form
  action="{{url_for('movies_list_bp.create_movie')}}"
  method="POST"
  class="form-container"
>
  <div class="form-element">
    <label for="name">Name</label>
    <input type="text" placeholder="John Wick" id="name" required name="name" />
  </div>
  <div class="form-element">
    <label for="poster">Poster</label>
    <input
      type="text"
      placeholder="http://"
      id="poster"
      required
      name="poster"
    />
  </div>
  <div class="form-element">
    <label for="rating">Rating</label>
    <input
      type="number"
      placeholder="8"
      id="rating"
      required
      min="1"
      max="10"
      name="rating"
    />
  </div>
  <div class="form-element">
    <label for="summary">Summary</label>
    <input
      type="text"
      placeholder="Awesome movie"
      id="summary"
      required
      name="summary"
    />
  </div>
  <div class="form-element">
    <label for="trailer">Trailer</label>
    <input
      type="text"
      placeholder="http://"
      id="trailer"
      required
      name="trailer"
    />
  </div>

  <button type="submit">Add Movie</button>
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
      integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <style>
      body {
        font-family: Roboto, sans-serif;
        padding: 16px;
      }

      .nav-link-container {
        display: flex;
        list-style: none;
        gap: 24px;
        padding: 0px;
      }

      .nav-link-container a {
        text-decoration: none;
      }

      .nav-link-container a:hover {
        color: skyblue;
      }

      nav {
        display: flex;
        justify-content: space-between;
      }
    </style>

    {% block head_content %} {% endblock %}
  </head>
  <body>
    <header>
      <nav>
        <ul class="nav-link-container">
          <li><a href="/">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/profile">Profile</a></li>
          <li><a href="/movie-list">Movies</a></li>
          <li><a href="/movie-list/new">Add Movie</a></li>
        </ul>

        <ul class="nav-link-container">
          {% if current_user.is_authenticated %}
          <li><a href="/logout">Logout</a></li>
          <li><p>{{current_user.username}}</p></li>
          {% else %}
          <li><a href="/login">Login</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    {% block content %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

<!-- Template inheritance Base / Parent-->

templates/home.html
{% extends "base.html" %} {% block content %}
<h1>Welcome to the Movie app 🎊🎊</h1>

{% endblock %}

templates/login.html
{% extends "base.html" %} {% block head_content %}
<style>
  .form-element {
    display: flex;
    flex-direction: column;
  }

  .form-container {
    display: flex;
    flex-direction: column;
    gap: 16px;
    max-width: 500px;
  }
  body {
    padding: 20px;
  }
</style>
{% endblock %} {% block content %}

<!-- BP.FN -->
<form
  action="{{url_for('auth_bp.submit_login_page')}}"
  method="POST"
  class="form-container"
>
  <div class="form-element">
    <label for="username">Username</label>
    <input
      type="text"
      placeholder="JohnDoe"
      id="username"
      required
      name="username"
    />
  </div>
  <div class="form-element">
    <label for="password">Password</label>
    <input type="password" id="password" required name="password" />
  </div>

  {% if password == confirm %}
  <button type="submit">Login</button>
  {% endif %}
</form>

{% endblock %}

templates/movie-details.html
{% extends "base.html" %} {% block head_content %}
<style>
  body {
    margin: 0;
    min-height: 100vh;
    display: grid;
    /* place-content: center; */

    font-family: Roboto, sans-serif;
  }

  .movie-spec {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .movie-summary {
    color: #7c6e6e;
  }

  .movie-container {
    /* background: orange; */
    padding: 24px;
    max-width: 800px;
  }
</style>

{% endblock %} {% block content %}

<section class="movie-detail-container">
  <iframe
    width="100%"
    height="800"
    src="{{movie.trailer}}"
    title="Ratatouille (2007) Trailer #1 | Movieclips Classic Trailers"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
    referrerpolicy="strict-origin-when-cross-origin"
    allowfullscreen
  ></iframe>
  <div class="movie-container">
    <div class="movie-spec">
      <h2 class="movie-name">{{movie.name}}</h2>
      <h2 class="movie-rating">⭐ {{movie.rating}}</h2>
    </div>
    <p class="movie-summary">{{movie.summary}}</p>
  </div>
</section>
{% endblock %}

templates/movie-list.html
{% extends "base.html" %} {% block head_content %}
<style>
  body {
    min-height: 100vh;
    display: grid;
    /* place-content: center; */

    font-family: Roboto, sans-serif;
  }

  .movie-container {
    /* background: orange; */
    width: 400px;
  }

  .movie-poster {
    width: 100%;
    height: 500px;
    object-fit: cover;

    border-radius: 20px;
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
  }

  .movie-spec {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 16px 0px;
  }

  .movie-summary {
    color: #7c6e6e;
  }

  /* .movie-list-container {
    display: flex;
    justify-content: space-around;
    padding: 24px;
    gap: 16px;
    flex-wrap: wrap;
  } */
  .movie-list-container {
    padding: 24px;
    display: grid;
    /* RAM */
    grid-template-columns: repeat(auto-fit, minmax(420px, 1fr));
    justify-items: center;
    gap: 24px;
  }

  .movie-name {
    text-decoration: none;
    font-size: 24px;
  }
</style>

{% endblock %} {% block content %}
<section class="movie-list-container">
  {% for movie in movies %}
  <div class="movie-container">
    <img src="{{movie.poster}}" alt="{{movie.name}}" class="movie-poster" />
    <div class="movie-spec">
      <!-- <a href="/movie-list/{{movie.id}}" class="movie-name">{{movie.name}}</a> -->
      <a
        href="{{url_for('movies_list_bp.movie_details_page', id=movie.id)}}"
        class="movie-name"
        >{{movie.name}}</a
      >
      <h4 class="movie-rating">⭐ {{movie.rating}}</h4>
    </div>
    <p class="movie-summary">{{movie.summary}}</p>

    <form
      action="{{url_for('movies_list_bp.delete_movie_by_id', id=movie.id)}}"
      method="POST"
      class="form-container"
    >
      <button type="submit" class="btn bthn-danger">
        Delete <i class="fa-solid fa-trash"></i>
      </button>
    </form>

    <!-- Task 1.2. Add delete button -->
    <!-- Task 1.3 Integration -->
  </div>
  {% endfor %}
</section>

{% endblock %}

templates/not_found.html
{% extends "base.html" %} {% block content %}

<img
  src="https://miro.medium.com/v2/resize:fit:1400/1*-Lv7y_W3qoO1fqsCii7jEA.gif"
  alt="Not found page"
/>

{% endblock %}

templates/profile.html
{% extends "base.html" %} {% block head_content %}

<style>
  .user-name {
    font-style: italic;
    font-weight: bold;
  }

  .user-pic {
    height: 225px;
    aspect-ratio: 1 / 1;
    border-radius: 50%;
    object-fit: cover;
  }

  .user-container {
    text-align: center;
    margin-bottom: 32px;
  }

  .verified {
    color: oklch(0.623 0.214 259.815);
  }
</style>

{% endblock %} {% block content %} {% for user in users %}
<div class="user-container">
  <img class="user-pic" src="{{user.pic}}" alt="profile picture" />
  <p>
    Hello, <span class="user-name">{{user.name}}</span>
    <!-- Conditional Rendering -->
    {% if user.isVerified %}
    <span class="verified"><i class="fa-solid fa-circle-check"></i></span>
    {% endif %}
  </p>
</div>
{% endfor %} {% endblock %}

templates/signup.html
{% extends "base.html" %} {% block head_content %}
<style>
  .form-element {
    display: flex;
    flex-direction: column;
  }

  .form-container {
    display: flex;
    flex-direction: column;
    gap: 16px;
    max-width: 500px;
  }
  body {
    padding: 20px;
  }
</style>
{% endblock %} {% block content %}

<!-- BP.FN -->
<form
  action="{{url_for('auth_bp.submit_signup_page')}}"
  method="POST"
  class="form-container"
>
  <div class="form-element">
    <label for="username">Username</label>
    <input
      type="text"
      placeholder="JohnDoe"
      id="username"
      required
      name="username"
    />
  </div>
  <div class="form-element">
    <label for="password">Password</label>
    <input type="password" id="password" required name="password" />
  </div>
  <div class="form-element">
    <label for="confirm">Confirm Password</label>
    <input type="password" id="confirm" required name="confirm" />
  </div>

  {% if password == confirm %}
  <button type="submit">Sign Up</button>
  {% endif %}
</form>

{% endblock %}